package _13_TestingAndValidation.ejercicios._06_JUnitExcepcion;
/* 
import org.junit.Test;
import static org.junit.Assert.*;

public class _06_JUnitExcepcion {
    public void validarPositivo(int n) {
        if (n < 0) throw new IllegalArgumentException("NÃºmero negativo no permitido");
    }

    @Test(expected = IllegalArgumentException.class)
    public void testValidarPositivo() {
        validarPositivo(-5);
    }
}
    */
